{
 "title": "Bed room",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Vonkajšia teplota",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "meteo-point",
     "query": "SELECT \"temperature_t2\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "temperature_t2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "locationId", "operator": "=", "value": "espruino_005" }
     ],
     "target": "{\"pointId\":\"espruino_005\",\"dimension\":\"temperature\",\"temperatureKey\":\"t2\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Teplota v spálni",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "meteo-point",
     "query": "SELECT \"temperature_t3\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "temperature_t3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "locationId", "operator": "=", "value": "espruino_005" }
     ],
     "target": "{\"pointId\":\"espruino_005\",\"dimension\":\"temperature\",\"temperatureKey\":\"t3\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Aktuálna vlhkosť",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"humidity\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"espruino_005\",\"dimension\":\"humidity\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Aktuálny tlak",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "meteo-point",
     "query": "SELECT \"pressure\" FROM \"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "locationId", "operator": "=", "value": "espruino_005" }
     ],
     "target": "{\"pointId\":\"location_001\",\"dimension\":\"pressure\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "measurement": "meteo-point",
     "query": "SELECT \"temperature_t3\", \"temperature_t2\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature_t2" ], "type": "field" }
      ],
      [
       { "params": [ "temperature_t3" ], "type": "field" }
      ],
      [
       { "params": [ "temperature_t1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "locationId", "operator": "=", "value": "espruino_005" }
     ],
     "target": "{\"pointId\":\"espruino_005\",\"temperatureKeys\":[\"t2\",\"t3\"]}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "pressure",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"pressure\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"espruino_005\",\"temperatureKeys\":[\"t2\",\"t3\"]}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"humidity\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"espruino_005\",\"dimensions\":[\"humidity\"]}",
     "type": "timeserie"
    }
   ]
  }
 ]
}