{
 "title": "Living room",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Teplota v izbe",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_t5\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'location_004') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_004\",\"dimension\":\"temperature\",\"temperatureKey\":\"t5\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Aktuálna vlhkosť",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"humidity\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'location_004') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_004\",\"dimension\":\"humidity\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_t5\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'location_004') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_004\",\"temperatureKeys\":[\"t5\"]}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"humidity\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'location_004') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"espruino_005\",\"dimensions\":[\"humidity\"]}",
     "type": "timeserie"
    }
   ]
  }
 ]
}