{
 "title": "Temperatures",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Vonkajšia teplota",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_t2\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'espruino_005') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_001\",\"dimension\":\"temperature\",\"temperatureKey\":\"t2\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Vonkajšia teplota 2",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_t2\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_002\",\"dimension\":\"temperature\",\"temperatureKey\":\"t2\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Teplota v spálni",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "meteo-point",
     "query": "SELECT \"temperature_t3\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'arduino_006') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "temperature_t3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "locationId", "operator": "=", "value": "espruino_005" }
     ],
     "target": "{\"pointId\":\"espruino_005\",\"dimension\":\"temperature\",\"temperatureKey\":\"t3\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Living room",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_t5\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'location_004') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_004\",\"dimension\":\"temperature\",\"temperatureKey\":\"t5\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Laudery room",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_t1\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'espruino_005') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_001\",\"dimension\":\"temperature\",\"temperatureKey\":\"t3\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Kid's room",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_t5\" FROM \"autogen\".\"meteo-sensor-point\" WHERE (\"locationId\" = 'location_003') AND $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "{\"pointId\":\"location_003\",\"dimension\":\"temperature\",\"temperatureKey\":\"t5\"}",
     "type": "timeserie"
    }
   ]
  }
 ]
}